version: '3.9'

services:
  embed_generator:
    container_name: EmbedGenerator
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      net:
        ipv4_address: 172.50.0.2
    # ports:
    #   - "3000:3000"
    volumes:
      - app:/usr/src/app

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.50.0.0/24"
          gateway: "172.50.0.1"

volumes:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker